In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sqlite3

In [16]:
##connevtion with DB
conn = sqlite3.connect('customer_churn.db')
sql_query="""
 SELECT name FROM sqlite_master WHERE type='table';
"""
tables= pd.read_sql(sql_query,conn)
##Create dataDrame for each Table
for table_name in tables['name']:
    df=pd.read_sql(f"Select * from {table_name}", conn)
    globals()[f"df_{table_name}"]=df
    print(f"created df:df_{table_name}")
conn.close()

created df:df_db_customer
created df:df_db_subscription
created df:df_db_support

In [22]:
df_db_customer.columns

Index(['customerid', 'name', 'country', 'state', 'gender', 'dob', 'interests',
       'pincode'],
      dtype='str')

In [23]:
df_db_subscription.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score'],
      dtype='str')

In [24]:
df_db_support.columns

Index(['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1',
       'comment'],
      dtype='str')

In [25]:
df_db_customer.head()

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [ ]:
##Data Cleaning

In [26]:
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     str
 1   name        21 non-null     str
 2   country     18 non-null     str
 3   state       21 non-null     str
 4   gender      21 non-null     str
 5   dob         21 non-null     str
 6   interests   4 non-null      str
 7   pincode     0 non-null      object
dtypes: object(1), str(7)
memory usage: 1.4+ KB

In [30]:
df_db_customer.rename(columns={'name':'Customer_name'},inplace=True)

In [34]:
##Drop columns
##df_db_customer.drop(df_db_customer.columns[-2:],axis=1,)
df_db_customer.drop(columns=['interests','pincode'],inplace=True)

In [39]:
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     str
 1   Customer_name  21 non-null     str
 2   country        18 non-null     str
 3   state          21 non-null     str
 4   gender         21 non-null     str
 5   dob            21 non-null     str
dtypes: str(6)
memory usage: 1.1 KB

In [42]:
## Change the dob columns datatype to DateTime
df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

In [49]:
##Replace the gender column
df_db_customer['gender']=df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

In [47]:
df_db_customer

    customerid Customer_name country          state  gender        dob
0   0002-ORFBO        keshav   India    Maharashtra    Male 1982-04-12
1   0003-MKNFE        raghav   India      Karnataka    Male 1995-11-23
2   0004-TLHLJ        lalita   India          Delhi  Female 1978-02-15
3   0011-IGKFF         mohan   India       Nagaland    Male 2001-08-30
4   0013-EXCHZ          mira   India          Delhi  Female 1990-05-05
5   0013-MHZWF         durga     NaN          Delhi   Women 1988-12-10
6   0013-SMEOE          mina   India      Meghalaya  Female 1976-09-21
7   0014-BMAQU         madan   India      Rajasthan    Male 1999-03-14
8   0015-UOCOJ          maya     NaN      Kathmandu   Women 1985-07-07
9   0016-QLJIS         arjun   Nepal      Kathmandu    Male 1993-10-29
10  0017-DINOC         shiva   India    Maharashtra     Men 1997-01-22
11  0017-IUDMW     rangadevi   India      Karnataka  Female 1981-06-18
12  0018-NYROU        chitra     NaN      Telangana  Female 2004-12-01
13  0019-EFAEP          raju   India      Meghalaya  Female 1992-04-25
14  0019-GFNTW        Madhav   India  Uttar Pradesh     Men 1979-11-11
15  0020-INWCK       parvati   India          Delhi  Female 1986-02-28
16  0020-JDNXP         rikim   India      Meghalaya  Female 1994-08-19
17  0021-IKXGC      vishakha   India      Rajasthan  Female 2000-09-02
18  0022-TCJCI    raghvendra   India      Telangana    Male 1983-12-30
19  0023-HGHWL       rishabh   India  Uttar Pradesh     Men 1991-05-14
20  0023-UYUPN        sudevi   India    Maharashtra   Women 1977-10-06